<!doctype html>
<html lang="uz">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Buxoro Invest | Investitsion obyektlar xaritasi</title>
<meta name="description" content="Buxoro viloyatidagi E-auksion investitsion lotlari xaritasi">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css">
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.Default.css">
<style>
:root{--red:#ed4549;--green:#2d4a6f;--ink:#172334;--muted:#738092;--line:#dfe4e8;--white:#fff;--blue:#174d79}
*{box-sizing:border-box}html,body,#map{height:100%;margin:0}body{font-family:Inter,"Segoe UI",Arial,sans-serif;color:var(--ink);overflow:hidden;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}button,input,select{font:inherit}
#map{position:absolute;inset:0;background:#d8d6ce}.leaflet-control-attribution{font-size:10px}.leaflet-bar a{color:#263643}
.topbar{position:absolute;z-index:950;top:0;left:0;right:0;height:72px;display:flex;align-items:center;padding:0 max(24px,calc((100vw - 1280px)/2));background:#fff;border-top:3px solid #2d4a6f;box-shadow:0 2px 12px #1d35481a}.brand{height:69px;display:flex;align-items:center}.brand-mark{width:42px;height:38px;margin-right:11px;position:relative}.brand-mark:before,.brand-mark:after{content:'';position:absolute;border-radius:12px 3px 12px 3px;transform:skewY(-18deg)}.brand-mark:before{width:32px;height:29px;left:1px;top:4px;background:linear-gradient(135deg,#6f8dac,#2d4a6f)}.brand-mark:after{width:23px;height:21px;right:0;top:8px;background:#1d314b;clip-path:polygon(0 50%,100% 0,100% 100%)}.brand strong{display:block;font-size:16px;letter-spacing:.025em;color:#1d282f}.brand small{display:block;font-size:9px;color:#83909a;margin-top:3px;letter-spacing:.04em;font-weight:600}
.map-tools{position:absolute;z-index:900;top:86px;left:14px;right:68px;display:flex;align-items:center;gap:10px;pointer-events:none}.map-tools>*{pointer-events:auto}.search{width:min(440px,38vw);height:48px;background:#ffffffef;border:1px solid #fff;border-radius:9px;box-shadow:0 5px 18px #26384625;display:flex;align-items:center;transition:.2s;backdrop-filter:blur(12px)}.search:focus-within{background:#fff;border-color:#8eb2ce;box-shadow:0 0 0 4px #3d7fab14}.search input{border:0;outline:0;width:100%;height:100%;padding:0 16px;background:transparent;font-size:13px;color:#243644}.search button{border:0;background:#f2f7f9;width:34px;height:34px;margin-right:7px;border-radius:8px;color:#41647d;cursor:pointer;font-size:18px}
.portfolio-badge{margin-left:auto;display:flex;align-items:center;gap:8px;padding:8px 13px;border-radius:10px;background:#edf2f7;color:#2d4a6f;white-space:nowrap}.portfolio-badge i{width:8px;height:8px;border-radius:50%;background:#2d4a6f;box-shadow:0 0 0 4px #2d4a6f1c}.portfolio-badge span{font-size:9px;text-transform:uppercase;letter-spacing:.06em;font-weight:700}.portfolio-badge b{font-size:13px;color:#1d314b}
.filters{margin-left:auto;height:48px;display:flex;align-items:stretch;gap:0;background:#ffffffef;border:1px solid #fff;border-radius:9px;box-shadow:0 5px 18px #26384625;backdrop-filter:blur(12px)}.filter-icon{width:40px;display:grid;place-items:center;color:#436177}.filter-icon svg{width:17px;height:17px;display:block;stroke:currentColor;stroke-width:1.8;fill:none;stroke-linecap:round;stroke-linejoin:round}.filter-field{position:relative;min-width:180px;padding:6px 30px 4px 12px;border-left:1px solid #e4e9ed}.filter-field label{display:block;font-size:8px;line-height:1;text-transform:uppercase;letter-spacing:.09em;color:#8995a0;font-weight:800;margin:1px 0 3px;pointer-events:none}.filter-field select{width:100%;height:26px;border:0;padding:0 18px 0 0;background:transparent;color:#273b4b;font-size:12px;font-weight:600;outline:0;cursor:pointer;appearance:none}.filter-field:after{content:'';position:absolute;right:14px;top:20px;width:6px;height:6px;border-right:1.5px solid #536979;border-bottom:1.5px solid #536979;transform:rotate(45deg);pointer-events:none}
.back{position:absolute;z-index:890;top:146px;left:14px;background:#fff;border:0;border-radius:6px;padding:10px 14px;box-shadow:0 2px 10px #26384630;font-weight:600;font-size:12px;cursor:pointer}.status{position:absolute;z-index:890;right:14px;bottom:20px;background:#fff;border-radius:8px;box-shadow:0 2px 15px #26384635;padding:9px 13px;min-width:210px}.status-row{display:flex;align-items:center;gap:9px;font-size:12px;padding:5px 0}.dot{width:11px;height:15px;border-radius:8px 8px 8px 0;transform:rotate(-45deg);background:var(--red);position:relative}.dot.green{background:var(--green)}.status-row b{margin-left:auto}.hint{position:absolute;z-index:890;left:14px;bottom:18px;background:#ffffffef;border-radius:6px;box-shadow:0 2px 12px #26384625;padding:8px 11px;font-size:10px;color:#66717d;max-width:310px}
.drawer{position:absolute;z-index:940;top:72px;bottom:0;left:0;width:390px;background:#fff;box-shadow:8px 0 25px #1d293835;transform:translateX(-105%);transition:transform .25s ease;display:flex;flex-direction:column}.drawer.open{transform:none}.drawer-close{position:absolute;right:14px;top:14px;width:36px;height:36px;border:1px solid #d9dee2;border-radius:50%;background:#fffffff2;box-shadow:0 2px 10px #1d293830;font-size:21px;line-height:1;cursor:pointer;z-index:2;color:#33404b}.drawer:not(.open) .drawer-close{display:none}.drawer-image{width:100%;height:220px;object-fit:cover;background:#eef1f3}.drawer-body{padding:21px 22px 30px;overflow:auto}.eyebrow{font-size:11px;font-weight:700;color:var(--red);text-transform:uppercase;letter-spacing:.08em}.drawer h1{font-size:19px;line-height:1.45;margin:8px 0 17px}.price{font-size:20px;font-weight:800;color:#173d5c;margin-bottom:18px}.info{border-top:1px solid var(--line)}.info-row{display:grid;grid-template-columns:118px 1fr;gap:10px;border-bottom:1px solid var(--line);padding:12px 0;font-size:12px;line-height:1.45}.info-row span{color:#7b8792}.info-row b{font-weight:600}.source{display:block;margin-top:18px;background:var(--red);color:#fff;text-align:center;text-decoration:none;padding:12px;border-radius:6px;font-size:13px;font-weight:700}
.pin{width:27px;height:36px;filter:drop-shadow(0 2px 2px #3336)}.pin-head{width:24px;height:24px;border-radius:50% 50% 50% 0;background:var(--red);border:2px solid #fff;transform:rotate(-45deg);position:relative}.pin-head:after{content:'';position:absolute;width:7px;height:7px;background:#fff;border-radius:50%;left:6.5px;top:6.5px}.pin.active .pin-head{background:var(--green)}
.marker-cluster-small,.marker-cluster-medium,.marker-cluster-large{background:#ee424680!important}.marker-cluster div{background:#fff!important;color:#26333e!important;border:6px solid var(--red);width:42px!important;height:42px!important;margin:0!important;border-radius:50%!important;display:grid!important;place-items:center;font-weight:700;box-shadow:0 2px 6px #2224}.marker-cluster span{line-height:1!important}.marker-cluster{background:transparent!important;width:42px!important;height:42px!important}
.server-cluster{width:44px;height:44px;border-radius:50%;display:grid;place-items:center;background:#fff;border:6px solid var(--red);color:#26333e;font-size:12px;font-weight:800;box-shadow:0 2px 8px #2225}.server-cluster.large{width:50px;height:50px;border-width:7px;font-size:11px}
.region-label{background:transparent;border:0;box-shadow:none;color:#7f567c;font:italic 12px Georgia;white-space:nowrap}.leaflet-overlay-pane svg path{vector-effect:non-scaling-stroke}
.leaflet-container .leaflet-interactive:focus,.leaflet-container path:focus,.leaflet-marker-icon:focus{outline:none!important;box-shadow:none!important}
.leaflet-top.leaflet-right{top:142px;right:4px}.leaflet-control-zoom{border:0!important;box-shadow:0 4px 18px #26384626!important}.leaflet-control-zoom a{width:38px!important;height:36px!important;line-height:34px!important;border-color:#e0e5e9!important}
.loading{position:absolute;z-index:1000;left:50%;top:50%;transform:translate(-50%,-50%);background:#fff;padding:12px 18px;border-radius:7px;box-shadow:0 3px 20px #26384640;font-size:12px}.hidden{display:none}
@media(max-width:1180px){.portfolio-badge{display:none}}
@media(max-width:850px){.topbar{height:58px;padding:0 16px}.brand{height:55px}.brand strong{font-size:15px}.brand small{display:none}.map-tools{top:68px;left:10px;right:10px;gap:8px;align-items:stretch;flex-wrap:wrap}.search{width:100%;height:44px;border-radius:10px}.filters{width:100%;height:48px;margin-left:0;border-radius:10px}.filter-icon{width:38px;flex:0 0 38px}.filter-field{flex:1;min-width:0;padding-left:12px}.back{top:178px;left:10px;padding:9px 13px}.leaflet-top.leaflet-right{top:174px;right:6px}.drawer{top:58px;width:min(390px,calc(100vw - 28px))}.hint{display:none}.status{bottom:10px;right:10px;min-width:170px}.status-row{font-size:11px}.drawer-image{height:180px}}
@media(max-width:520px){.topbar{padding:0 12px}.map-tools{left:8px;right:8px}.filter-field{padding-right:22px;padding-left:9px}.filter-field label{font-size:7px}.filter-field select{font-size:11px}.filter-field:after{right:10px}.back{left:8px}.leaflet-top.leaflet-right{right:4px}.status{max-width:calc(100vw - 16px)}}
</style>
<style>.map-links{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.map-link{display:flex;align-items:center;justify-content:center;gap:7px;padding:10px 8px;border-radius:7px;background:#f3f6fa;color:#243b55;text-decoration:none;font-size:11px;font-weight:700;border:1px solid #e4eaf0}.map-link:hover{background:#e8eef5}.map-link.google{color:#315d9a}.map-link.yandex{color:#d83e3e}.map-link svg{width:16px;height:16px}</style>
<style>.filter-field.enhanced:after{top:20px;transition:transform .18s}.filter-field.enhanced.open:after{transform:rotate(225deg);top:23px}.native-select{position:absolute!important;inset:0!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important}.select-trigger{height:26px;display:flex;align-items:center;padding-right:17px;color:#273b4b;font-size:12px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:pointer;user-select:none}.select-menu{display:none;position:absolute;z-index:1000;top:calc(100% + 8px);left:0;right:0;min-width:220px;max-height:310px;overflow:auto;padding:6px;background:#fff;border:1px solid #dce4eb;border-radius:10px;box-shadow:0 14px 38px #1d314b30}.filter-field.open .select-menu{display:block}.select-option{width:100%;display:flex;align-items:center;justify-content:space-between;border:0;border-radius:7px;padding:10px 11px;background:#fff;color:#2b3e50;text-align:left;font-size:12px;line-height:1.3;cursor:pointer}.select-option:hover{background:#eef3f8;color:#2d4a6f}.select-option.selected{background:#2d4a6f;color:#fff;font-weight:700}.select-menu::-webkit-scrollbar{width:6px}.select-menu::-webkit-scrollbar-thumb{background:#b9c6d3;border-radius:10px}@media(max-width:520px){.select-menu{position:fixed;top:auto;left:8px;right:8px;bottom:12px;max-height:48vh;border-radius:14px;padding:8px}.select-option{padding:12px}}</style>
</head>
<body>
<div id="map"></div><div id="loading" class="loading">Lotlar xaritaga joylanmoqda…</div>
<div class="topbar">
 <div class="brand"><div><strong>BUXORO INVEST</strong><small>INVESTITSIYA PORTALI</small></div></div>
</div>
<div class="map-tools">
 <div class="search"><input id="q" placeholder="Lot raqami, nomi yoki manzil bo‘yicha izlash"><button aria-label="Qidirish">⌕</button></div>
 <div class="portfolio-badge"><i></i><span>Faol portfel</span><b id="menuTotal">—</b></div>
 <div class="filters"><span class="filter-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 6h16M7 12h10M10 18h4"/></svg></span><div class="filter-field"><label for="group">Obyekt toifasi</label><select id="group"><option value="">Barcha toifalar</option></select></div><div class="filter-field"><label for="district">Hudud</label><select id="district"><option value="">Barcha hududlar</option></select></div></div>
</div>
<button class="back" id="wholeUz">↶ Butun O‘zbekiston</button>
<div class="hint">Xaritada faqat E-auksion lot kartasidan tasdiqlangan koordinatalar ko‘rsatiladi.</div>
<div class="status"><div class="status-row"><i class="dot green"></i><span>Xaritada ko‘rsatilgan</span><b id="shown">0</b></div><div class="status-row"><i class="dot"></i><span>Jami topilgan</span><b id="total">0</b></div></div>
<aside class="drawer" id="drawer"><button class="drawer-close" id="closeDrawer">×</button><img id="dImage" class="drawer-image" alt="Lot rasmi"><div class="drawer-body"><div id="dGroup" class="eyebrow"></div><h1 id="dTitle"></h1><div id="dPrice" class="price"></div><div class="info"><div class="info-row"><span>Lot raqami</span><b id="dLot"></b></div><div class="info-row"><span>Hudud</span><b id="dDistrict"></b></div><div class="info-row"><span>Manzil</span><b id="dAddress"></b></div><div class="info-row"><span>Auksion sanasi</span><b id="dDate"></b></div></div><a id="dSource" class="source" target="_blank" rel="noopener">E-auksionda ko‘rish →</a></div></aside>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script src="https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster.js"></script>
<script>
const map=L.map('map',{zoomControl:false,minZoom:5,maxZoom:15}).setView([41.15,64.4],6);L.control.zoom({position:'topright'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:18}).addTo(map);
const clusters=L.markerClusterGroup({showCoverageOnHover:false,maxClusterRadius:42,spiderfyOnMaxZoom:true,disableClusteringAtZoom:12});map.addLayer(clusters);const serverClusters=L.featureGroup().addTo(map);const exactShapes=L.featureGroup().addTo(map);
let regionLayer,activeMarker,state={q:'',group:'',district:''},summary,markerRequest,polygonRequest,polygonTimer,markerTimer;
const lotIndex=new Map();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>new Intl.NumberFormat('uz-UZ',{maximumFractionDigits:0}).format(Number(n||0))+' so‘m';
const pinIcon=active=>L.divIcon({className:'',html:`<div class="pin ${active?'active':''}"><div class="pin-head"></div></div>`,iconSize:[27,36],iconAnchor:[12,34]});
const clusterIcon=count=>L.divIcon({className:'',html:`<div class="server-cluster ${count>999?'large':''}">${new Intl.NumberFormat('uz-UZ',{notation:count>999?'compact':'standard'}).format(count)}</div>`,iconSize:[50,50],iconAnchor:[25,25]});
async function boundaries(){const data=await fetch('/geo/uzbekistan-regions.geojson').then(r=>r.json());regionLayer=L.geoJSON(data,{style:f=>({color:f.properties.ADM1_UZ==='Buxoro viloyati'?'#2d4a6f':'#96989a',weight:f.properties.ADM1_UZ==='Buxoro viloyati'?3:2,fillColor:'#fff',fillOpacity:f.properties.ADM1_UZ==='Buxoro viloyati'?.68:.28}),onEachFeature:(f,l)=>{l.bindTooltip(f.properties.ADM1_UZ,{permanent:false,className:'region-label'});if(f.properties.ADM1_UZ==='Buxoro viloyati')window.buxoroBounds=l.getBounds()}}).addTo(map);regionLayer.bringToBack()}
async function loadSummary(){summary=await fetch('/api/summary').then(r=>r.json());document.querySelector('#menuTotal').textContent=new Intl.NumberFormat('uz-UZ').format(summary.total)+' ta';document.querySelector('#group').innerHTML='<option value="">Barcha toifalar</option>'+summary.groups.map(x=>`<option value="${esc(x.group_name)}">${esc(x.group_name)} (${x.count})</option>`).join('');document.querySelector('#district').innerHTML='<option value="">Barcha hududlar</option>'+summary.districts.sort((a,b)=>a.district.localeCompare(b.district)).map(x=>`<option value="${esc(x.district)}">${esc(x.district)} (${x.count})</option>`).join('')}
async function loadMarkers(){
 const loading=document.querySelector('#loading');loading.classList.remove('hidden');
 if(markerRequest)markerRequest.abort();markerRequest=new AbortController();const request=markerRequest;
 const padded=map.getBounds().pad(.15),p=new URLSearchParams({zoom:map.getZoom()});if(!state.q)Object.entries({south:padded.getSouth(),north:padded.getNorth(),west:padded.getWest(),east:padded.getEast()}).forEach(([k,v])=>p.set(k,v));Object.entries(state).forEach(([k,v])=>v&&p.set(k,v));
 try{
  const res=await fetch('/api/map-lots?'+p,{signal:request.signal}).then(r=>{if(!r.ok)throw new Error('Markerlar yuklanmadi');return r.json()});
  clusters.clearLayers();serverClusters.clearLayers();exactShapes.clearLayers();lotIndex.clear();
  document.querySelector('#shown').textContent=res.shown;document.querySelector('#total').textContent=res.total;
  const batch=[];res.data.forEach(lot=>{if(lot.type==='cluster'){const m=L.marker([lot.lat,lot.lng],{icon:clusterIcon(lot.count),keyboard:false});m.on('click',()=>map.setView([lot.lat,lot.lng],Math.min(12,map.getZoom()+2),{animate:true}));serverClusters.addLayer(m);return}lotIndex.set(String(lot.external_id),lot);const m=L.marker([lot.lat,lot.lng],{icon:pinIcon(false),keyboard:false});m.lot=lot;m.on('click',()=>openLot(m));batch.push(m)});
  clusters.addLayers(batch);schedulePolygons();
  if(state.q&&res.data.length===1)map.setView([res.data[0].lat,res.data[0].lng],13,{animate:true});
 }catch(error){if(error.name!=='AbortError')console.error(error)}finally{if(markerRequest===request)loading.classList.add('hidden')}
}
function schedulePolygons(){clearTimeout(polygonTimer);polygonTimer=setTimeout(loadVisiblePolygons,180)}
async function loadVisiblePolygons(){
 if(map.getZoom()<11){exactShapes.clearLayers();return}
 if(polygonRequest)polygonRequest.abort();polygonRequest=new AbortController();
 const b=map.getBounds(),p=new URLSearchParams({south:b.getSouth(),north:b.getNorth(),west:b.getWest(),east:b.getEast()});Object.entries(state).forEach(([k,v])=>v&&p.set(k,v));
 try{
  const res=await fetch('/api/map-polygons?'+p,{signal:polygonRequest.signal}).then(r=>{if(!r.ok)throw new Error('Poligonlar yuklanmadi');return r.json()});
  exactShapes.clearLayers();
  res.data.forEach(row=>{const lot=lotIndex.get(String(row.external_id));if(!lot||!row.geometry)return;const shape=L.geoJSON(row.geometry,{style:{color:'#2d4a6f',weight:2,fillColor:'#6f8dac',fillOpacity:.3}});shape.lot=lot;shape.on('click',()=>openLot(shape));exactShapes.addLayer(shape)});
 }catch(error){if(error.name!=='AbortError')console.error(error)}
}
function scheduleMarkers(){clearTimeout(markerTimer);markerTimer=setTimeout(loadMarkers,220)}
map.on('moveend zoomend',scheduleMarkers);
function renderLot(x){document.querySelector('#dImage').src=x.image_url||'';document.querySelector('#dImage').style.display=x.image_url?'block':'none';document.querySelector('#dGroup').textContent=x.group_name||'';document.querySelector('#dTitle').textContent=x.name||'Nomsiz obyekt';document.querySelector('#dPrice').textContent=money(x.start_price);document.querySelector('#dLot').textContent=x.lot_number||'—';document.querySelector('#dDistrict').textContent=x.district||'Buxoro viloyati';document.querySelector('#dAddress').textContent=x.address||'Ko‘rsatilmagan';document.querySelector('#dDate').textContent=x.auction_date||'—';document.querySelector('#dSource').href=x.source_url||'#';syncMapLinks()}
async function openLot(marker){
 if(activeMarker&&activeMarker.setIcon)activeMarker.setIcon(pinIcon(false));activeMarker=marker;if(marker.setIcon)marker.setIcon(pinIcon(true));
 const x=marker.lot;document.querySelector('#drawer').classList.add('open');
 if(x.loaded){renderLot(x);return}
 document.querySelector('#dImage').style.display='none';document.querySelector('#dGroup').textContent='';document.querySelector('#dTitle').textContent='Ma’lumot yuklanmoqda…';document.querySelector('#dPrice').textContent='';
 try{const detail=await fetch('/api/map-lots/'+encodeURIComponent(x.external_id)).then(r=>{if(!r.ok)throw new Error('Lot ma’lumoti yuklanmadi');return r.json()});Object.assign(x,detail,{loaded:true});if(activeMarker===marker)renderLot(x)}catch(error){if(activeMarker===marker)document.querySelector('#dTitle').textContent='Ma’lumotni yuklab bo‘lmadi';console.error(error)}
}
function syncMapLinks(){const x=activeMarker&&activeMarker.lot;if(!x||!x.lat||!x.lng)return;let box=document.querySelector('.map-links');if(!box){box=document.createElement('div');box.className='map-links';box.innerHTML='<a class="map-link google" target="_blank" rel="noopener"><span>📍</span>Google Maps</a><a class="map-link yandex" target="_blank" rel="noopener"><span>📍</span>Yandex Maps</a>';document.querySelector('.drawer-body').appendChild(box)}box.children[0].href='https://www.google.com/maps/search/?api=1&query='+x.lat+','+x.lng;box.children[1].href='https://yandex.com/maps/?pt='+x.lng+','+x.lat+'&z=16&l=map'}
new MutationObserver(syncMapLinks).observe(document.querySelector('#drawer'),{attributes:true,attributeFilter:['class']});
document.querySelector('#closeDrawer').onclick=()=>{document.querySelector('#drawer').classList.remove('open');if(activeMarker&&activeMarker.setIcon)activeMarker.setIcon(pinIcon(false));activeMarker=null};
document.querySelector('#wholeUz').onclick=()=>map.fitBounds(regionLayer.getBounds(),{padding:[20,20]});
document.querySelector('#group').onchange=e=>{state.group=e.target.value;loadMarkers()};document.querySelector('#district').onchange=e=>{state.district=e.target.value;const selected=summary?.districts.find(x=>x.district===state.district);if(selected)map.setView([selected.lat,selected.lng],10);else loadMarkers()};
let timer;document.querySelector('#q').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{state.q=e.target.value;loadMarkers()},450)};
function enhanceSelect(select){const field=select.closest('.filter-field');field.classList.add('enhanced');select.classList.add('native-select');const trigger=document.createElement('div');trigger.className='select-trigger';trigger.setAttribute('role','button');trigger.setAttribute('tabindex','0');const menu=document.createElement('div');menu.className='select-menu';field.append(trigger,menu);const render=()=>{const selected=select.options[select.selectedIndex];trigger.textContent=selected?selected.text:'Tanlang';menu.innerHTML=[...select.options].map(o=>`<button type="button" class="select-option${o.selected?' selected':''}" data-value="${esc(o.value)}">${esc(o.text)}</button>`).join('')};const toggle=()=>{document.querySelectorAll('.filter-field.open').forEach(x=>x!==field&&x.classList.remove('open'));field.classList.toggle('open')};trigger.onclick=e=>{e.stopPropagation();toggle()};trigger.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}if(e.key==='Escape')field.classList.remove('open')};menu.onclick=e=>{const option=e.target.closest('.select-option');if(!option)return;select.value=option.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));field.classList.remove('open');render()};new MutationObserver(render).observe(select,{childList:true,subtree:true});select.addEventListener('change',render);render()}
document.querySelectorAll('.filter-field select').forEach(enhanceSelect);document.addEventListener('click',()=>document.querySelectorAll('.filter-field.open').forEach(x=>x.classList.remove('open')));
Promise.all([boundaries(),loadSummary()]).then(()=>{if(window.buxoroBounds)map.fitBounds(window.buxoroBounds,{padding:[35,35],animate:false});return loadMarkers()}).catch(()=>{document.querySelector('#loading').textContent='Xaritani yuklab bo‘lmadi'});
</script>
</body></html>
